cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    test_user:
      email: test_user@email.com
      failed_login_attempts: 0
      logged_in: false
      name: Test User
      password: $2b$12$t.DvbrzfnwC6Yn0know2hOsC7MynYZnYYf8wHyAMk5WHCTmJQloo6
pre-authorized:
  emails:
  - test_user2@email.com
